### ISSUE TITLE
Upgrade SixLabors.ImageSharp

### ISSUE THREAD

**Issue by diegodfsd** [replaysMike/AnyBarcode#1]
Hi @replaysMike,

I'm using your package to generate barcodes but I need to upgrade a library used to generate pdf files, but when I update the pdf library the barcode process stops working. Analysing deeper the problem is that the pdf library upgrade the SixLabors.ImageSharp version and in the last updates SixLabors.ImageSharp has some break changes. So, I have the impression is necessary to upgrade the AnyBarcode dependencies, what do you think?

**Comment by replaysMike** [comment]
hey @diegodfsd - I'll take a look today, it's quite possible there are breaking changes in ImageSharp. I'll check and see what needs to be done to make that happen

**Comment by diegodfsd** [comment]
@replaysMike I did fork from your repo and I already have upgraded the packages. Unfortunately, at least one test was broken, the test that compares two images. When I went deep into the code I noticed that the resulting image has some crispy around the label text.

Take a look at some examples 

Image generated after the upgrade, but using DrawText overload with Pen
![UPCA](https://github.com/replaysMike/AnyBarcode/assets/705799/f3df4570-e66a-4b32-ad61-0e8bbd5b7b4a)

Image generated after the upgrade, but I'm using DrawText overload without pen
![UPCA](https://github.com/replaysMike/AnyBarcode/assets/705799/9b06e88e-f437-4c4a-a68f-9c02407d79ed)

Both of them are different from the expected image (ShouldGenerate_Upca_BarcodeWithLabel.png)

**Comment by diegodfsd** [comment]
Hi, @replaysMike. Please, share your comments about my last comment when you have time.

**Comment by replaysMike** [comment]
interesting, not surprising as ImageSharp often publishes breaking changes. I'm looking at this now and will see what the solution will be

**Comment by replaysMike** [comment]
This is now fixed in [v2.0.0](https://github.com/replaysMike/AnyBarcode/releases/tag/v.2.0.0)
